# Generated by Django 5.0.6 on 2024-05-18 20:33

import django.db.models.deletion
import ice_cream.models
import imagekit.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_alter_icecream_options_icecream_image_icecream_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=ice_cream.models.get_image_path, verbose_name='Зображення')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основне зображення')),
                ('ice_cream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ice_cream.icecream')),
            ],
        ),
    ]
